# Site wide configuration

title: "Molly Pierce - Graphic & Web Designer"
description: "Graphic + Website Design, Digital Marketing - Corpus Christi, TX"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: en
url: 'localhost:4000'
feed:
  path: atom.xml


# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

markdown:    kramdown


collections:
  portfolio:
      output: true
      permalink: /portfolio/:path/

# Site owner
owner:
  name: Molly Pierce
  email: http://hrmg.agency
  twitter:
  google:
    ad-client:
    ad-slot:
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:



include:
  - .htaccess
exclude:
